#!/usr/bin/env bash
set -uo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/assert.sh"
ROOT="$DIR/.."

jq empty "$ROOT/.claude-plugin/plugin.json"; assert_exit 0 $? "plugin.json valid json"
assert_eq "shadow-legion" "$(jq -r '.name' "$ROOT/.claude-plugin/plugin.json")" "plugin name"
assert_eq "./statusline/legion.sh" "$(jq -r '.statusline' "$ROOT/.claude-plugin/plugin.json")" "statusline declared"

jq empty "$ROOT/.claude-plugin/marketplace.json"; assert_exit 0 $? "marketplace.json valid json"
assert_eq "shadow-legion" "$(jq -r '.plugins[0].name' "$ROOT/.claude-plugin/marketplace.json")" "marketplace plugin name"
assert_eq "." "$(jq -r '.plugins[0].source' "$ROOT/.claude-plugin/marketplace.json")" "marketplace source is repo root"
# --- Monarch skill ---
sk="$ROOT/skills/monarch/SKILL.md"
assert_eq "1" "$([ -f "$sk" ] && echo 1 || echo 0)" "monarch SKILL.md exists"
assert_contains "$(sed -n '1,6p' "$sk")" "name: monarch" "monarch frontmatter name"
assert_contains "$(sed -n '1,6p' "$sk")" "description:" "monarch frontmatter description"
assert_eq "1" "$([ -s "$ROOT/output-styles/monarch.md" ] && echo 1 || echo 0)" "output style non-empty"
# --- Tusk agent (Phase 2: own worktree, not native isolation) ---
tk="$ROOT/agents/tusk.md"
fm="$(sed -n '1,12p' "$tk" 2>/dev/null)"
assert_contains "$fm" "name: tusk" "tusk name"
assert_contains "$fm" "model: sonnet" "tusk runs sonnet"
assert_contains "$fm" "maxTurns:" "tusk has maxTurns cap"
assert_eq "0" "$(grep -c 'isolation: worktree' "$tk" || true)" "tusk no longer uses native isolation"
assert_contains "$(cat "$tk")" "git worktree add" "tusk creates its own worktree"
# --- /experiment command ---
cm="$ROOT/commands/experiment.md"
cfm="$(sed -n '1,8p' "$cm" 2>/dev/null)"
assert_contains "$cfm" "description:" "experiment cmd description"
assert_contains "$cfm" "argument-hint:" "experiment cmd argument-hint"
assert_contains "$(cat "$cm")" "tusk" "experiment dispatches tusk"
assert_contains "$(cat "$cm")" "Id:" "experiment passes Id to tusk"
assert_eq "0" "$(grep -c 'isolation: worktree' "$cm" || true)" "experiment no longer references native isolation"
# --- /campaign command ---
cc="$ROOT/commands/campaign.md"
ccfm="$(sed -n '1,8p' "$cc" 2>/dev/null)"
assert_contains "$ccfm" "description:" "campaign cmd description"
assert_contains "$ccfm" "argument-hint:" "campaign cmd argument-hint"
body="$(cat "$cc")"
assert_contains "$body" "allocate.sh" "campaign uses allocate.sh seam"
assert_contains "$body" "tusk" "campaign dispatches tusk"
assert_contains "$body" "safety-screen.sh" "campaign safety-screens"
assert_contains "$body" "Concurrency" "campaign honors Concurrency"
# --- Phase 3: reasoned pruning wiring ---
cc="$ROOT/commands/campaign.md"; ccb="$(cat "$cc")"
assert_contains "$ccb" "dead-candidates" "campaign checks dead-candidates"
assert_contains "$ccb" "mark-dead" "campaign marks dead with reason"
assert_contains "$ccb" "graveyard" "campaign records graveyard"
tkb="$(cat "$ROOT/agents/tusk.md")"
assert_contains "$tkb" "graveyard" "tusk RECALL reads graveyard"
# --- Phase 4: recall skill ---
rk="$ROOT/skills/recall/SKILL.md"
assert_eq "1" "$([ -f "$rk" ] && echo 1 || echo 0)" "recall SKILL.md exists"
rkfm="$(sed -n '1,8p' "$rk")"
assert_contains "$rkfm" "name: recall" "recall frontmatter name"
assert_contains "$rkfm" "context: fork" "recall runs in fork context"
assert_contains "$(cat "$rk")" "kb.sh" "recall uses kb.sh"
# --- Phase 4: KB wiring ---
assert_contains "$(cat "$ROOT/agents/tusk.md")" "kb.sh" "tusk RECALL uses kb.sh"
ccb4="$(cat "$ROOT/commands/campaign.md")"
assert_contains "$ccb4" "kb.sh" "campaign uses kb.sh (recall/index)"
assert_contains "$ccb4" "recall" "campaign invokes recall at intake"
# --- Phase 5: proposal-only integration ---
ccb5="$(cat "$ROOT/commands/campaign.md")"
assert_contains "$ccb5" "propose.sh" "campaign uses propose.sh"
assert_contains "$ccb5" "PROPOSAL" "campaign writes PROPOSAL.md"
assert_eq "0" "$(printf '%s' "$ccb5" | grep -c 'gh pr create' || true)" "campaign no longer uses gh pr create"
assert_done
